# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2017 Andes Technology Corporation
# Rick Chen, Andes Technology Corporation <rick@andestech.com>

obj-y	:= cpu.o
# wh core did not support i/d cache operation
#obj-y	+= cache.o
obj-y   += timer.o

